name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: make DESTDIR=/tmp/pkg install

    - name: Install local
      run: make install-local

    - name: Install local symlink
      run: make install-local-symlink
